#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "sort.hpp"
#include "utils.hpp"
#include "page.hpp"

const int delay_time = 1;

void Sort::generateArray()
{
    std::uniform_int_distribution<int> random_range(1, square_rect.h / 10 - 1);
    main_vector.clear();
    for (int i = 0; i < square_rect.w / 10; i++)
    {
        main_vector.push_back(random_range(random_number));
    }
}

Sort::Sort(SDL_Renderer*& renderer, SDL_Texture* background_texture)
{
    thread_manager = std::thread(&Sort::threadManager, this, std::ref(renderer));
    cursor = nullptr;
    // Back button set up
    back_button = Utils::loadTexture("images/back_button.png", renderer);
    back_disable = Utils::loadTexture("images/back_disable.png", renderer);
    back_rect = {10, (HEIGHT * 10) - 185, 30, 30};

    // Change button set up
    change_button = Utils::loadTexture("images/change_button.png", renderer);
    change_disable = Utils::loadTexture("images/change_disable.png", renderer);
    change_rect = {back_rect.x + back_rect.w, (HEIGHT * 10) - 190, 180, 40};

    // Cancel button set up
    cancel_button = Utils::loadTexture("images/cancel_button.png", renderer);
    cancel_disable = Utils::loadTexture("images/cancel_disable.png", renderer);
    cancel_rect = {change_rect.x + change_rect.w, (HEIGHT * 10) - 185, 30, 30};

    // Selection sort button set up
    selection_sort_button = Utils::loadTexture("images/selection_sort_button.png", renderer);
    selection_sort_disable = Utils::loadTexture("images/selection_sort_disable.png", renderer);
    selection_sort_rect = {10, (HEIGHT * 10) - 130, 200, 50};

    // Insertion sort button set up
    insertion_sort_button = Utils::loadTexture("images/insertion_sort_button.png", renderer);
    insertion_sort_disable = Utils::loadTexture("images/insertion_sort_disable.png", renderer);
    insertion_sort_rect = {selection_sort_rect.x + selection_sort_rect.w + 10, (HEIGHT * 10) - 130, 200, 50};

    // Bubble sort button set up
    bubble_sort_button = Utils::loadTexture("images/bubble_sort_button.png", renderer);
    bubble_sort_disable = Utils::loadTexture("images/bubble_sort_disable.png", renderer);
    bubble_sort_rect = {insertion_sort_rect.x + insertion_sort_rect.w + 10, (HEIGHT * 10) - 130, 200, 50};

    // Interchange sort button set up
    interchange_sort_button = Utils::loadTexture("images/interchange_sort_button.png", renderer);
    interchange_sort_disable = Utils::loadTexture("images/interchange_sort_disable.png", renderer);
    interchange_sort_rect = {bubble_sort_rect.x + bubble_sort_rect.w + 10, (HEIGHT * 10) - 130, 200, 50};

    // Counting sort button set up
    counting_sort_button = Utils::loadTexture("images/counting_sort_button.png", renderer);
    counting_sort_disable = Utils::loadTexture("images/counting_sort_disable.png", renderer);
    counting_sort_rect = {selection_sort_rect.x, selection_sort_rect.y + selection_sort_rect.h + 10, 200, 50};

    // Quick sort button set up
    quick_sort_button = Utils::loadTexture("images/quick_sort_button.png", renderer);
    quick_sort_disable = Utils::loadTexture("images/quick_sort_disable.png", renderer);
    quick_sort_rect = {counting_sort_rect.x + counting_sort_rect.w + 10, counting_sort_rect.y, 200, 50};

    // Heap sort button set up
    heap_sort_button = Utils::loadTexture("images/heap_sort_button.png", renderer);
    heap_sort_disable = Utils::loadTexture("images/heap_sort_disable.png", renderer);
    heap_sort_rect = {quick_sort_rect.x + quick_sort_rect.w + 10, counting_sort_rect.y, 200, 50};

    // Merge sort button set up
    merge_sort_button = Utils::loadTexture("images/merge_sort_button.png", renderer);
    merge_sort_disable = Utils::loadTexture("images/merge_sort_disable.png", renderer);
    merge_sort_rect = {heap_sort_rect.x + heap_sort_rect.w + 10, counting_sort_rect.y, 200, 50};

    SDL_RenderClear(renderer);
    SDL_RenderCopy(renderer, background_texture, NULL, NULL);
    renderLayout(renderer);
    SDL_RenderPresent(renderer);
}


Sort::~Sort()
{
    do {
        exit_thread_manager = true;
    } while (!thread_manager.joinable());
    thread_manager.join();
}

void Sort::firstDraw(std::vector<int> vector, SDL_Renderer*& renderer)
{
    SDL_RenderSetScale(renderer, 10, 10);
    int index = 0;
    for (int i:vector)
    {
        SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
        SDL_RenderDrawLine(renderer, index + 1, square_rect.h / 10 - i, index + 1, square_rect.h / 10);
        index+=1;
    }
    SDL_RenderSetScale(renderer, 1, 1);
}

void Sort::renderLayout(SDL_Renderer*& renderer)
{
    SDL_RenderCopy(renderer, change_button, NULL, &change_rect);
    SDL_RenderCopy(renderer, back_button, NULL, &back_rect);
    SDL_RenderCopy(renderer, selection_sort_button, NULL, &selection_sort_rect);
    SDL_RenderCopy(renderer, cancel_disable, NULL, &cancel_rect);
    SDL_RenderCopy(renderer, insertion_sort_button, NULL, &insertion_sort_rect);
    SDL_RenderCopy(renderer, bubble_sort_button, NULL, &bubble_sort_rect);
    SDL_RenderCopy(renderer, interchange_sort_button, NULL, &interchange_sort_rect);
    SDL_RenderCopy(renderer, counting_sort_button, NULL, &counting_sort_rect);
    SDL_RenderCopy(renderer, quick_sort_button, NULL, &quick_sort_rect);
    SDL_RenderCopy(renderer, heap_sort_button, NULL, &heap_sort_rect);
    SDL_RenderCopy(renderer, merge_sort_button, NULL, &merge_sort_rect);

    SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
    square_rect = { 10, 10, (WIDTH * 10) - 20, (HEIGHT * 10) - 200 };
    SDL_RenderFillRect(renderer, &square_rect);
    generateArray();
    firstDraw(main_vector, renderer);
}

void Sort::sortAction(SDL_Event& event, bool& quit, SDL_Renderer*& renderer)
{
    while (SDL_PollEvent(&event) != 0) {
        if (!is_sorting)
        {
            if (event.type == SDL_QUIT) {
                quit = true;
            } else if (event.type == SDL_MOUSEMOTION) {
                change_hovered = Utils::isMouseOverButton(change_rect);
                back_hovered = Utils::isMouseOverButton(back_rect);
                selection_sort_hovered = Utils::isMouseOverButton(selection_sort_rect);
                insertion_sort_hovered = Utils::isMouseOverButton(insertion_sort_rect);
                bubble_sort_hovered = Utils::isMouseOverButton(bubble_sort_rect);
                interchange_sort_hovered = Utils::isMouseOverButton(interchange_sort_rect);
                counting_sort_hovered = Utils::isMouseOverButton(counting_sort_rect);
                quick_sort_hovered = Utils::isMouseOverButton(quick_sort_rect);
                heap_sort_hovered = Utils::isMouseOverButton(heap_sort_rect);
                merge_sort_hovered = Utils::isMouseOverButton(merge_sort_rect);

                if (selection_sort_hovered || back_hovered || change_hovered || insertion_sort_hovered
                || bubble_sort_hovered || interchange_sort_hovered || counting_sort_hovered ||
                 quick_sort_hovered || heap_sort_hovered || merge_sort_hovered) {
                    cursor = SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_HAND);
                    SDL_SetCursor(cursor);
                } else {
                    SDL_FreeCursor(cursor);
                }
            } else if (event.type == SDL_MOUSEBUTTONDOWN) {
                if (change_hovered) {
                    SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
                    SDL_RenderFillRect(renderer, &square_rect);
                    generateArray();
                    firstDraw(main_vector, renderer);
                    SDL_RenderPresent(renderer);
                } else if (back_hovered) {
                    destroy();
                    current_page = menu_page;
                } else if (selection_sort_hovered) {
                    vector<int> selection_sort_vector(main_vector.begin(), main_vector.end());
                    sort_thread = std::thread(&Sort::selectionSort, this, std::ref(renderer), std::ref(selection_sort_vector), std::ref(is_sorting));
                } else if (insertion_sort_hovered) {
                    sort_thread = std::thread(&Sort::insertionSort, this, std::ref(renderer));
                } else if (bubble_sort_hovered) {
                    sort_thread = std::thread(&Sort::bubbleSort, this, std::ref(renderer));
                } else if (interchange_sort_hovered) {
                    sort_thread = std::thread(&Sort::interchangeSort, this, std::ref(renderer));
                } else if (counting_sort_hovered) {
                    sort_thread = std::thread(&Sort::countingSort, this, std::ref(renderer));
                } else if (quick_sort_hovered) {
                    vector<int> sort_vector(main_vector.begin(), main_vector.end());
                    sort_thread = std::thread(&Sort::quickSort, this, std::ref(renderer), std::ref(sort_vector), 0, sort_vector.size() - 1);
                }
            }
        } else {
            if (event.type == SDL_MOUSEMOTION) {
                cancel_hovered = Utils::isMouseOverButton(cancel_rect);

                if (cancel_hovered) {
                    cursor = SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_HAND);
                    SDL_SetCursor(cursor);
                } else {
                    SDL_FreeCursor(cursor);
                }
            } else if (event.type == SDL_MOUSEBUTTONDOWN) {
                if (cancel_hovered) {
                    is_sorting = false;
                    sort_thread.join();
                    SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
                    SDL_RenderFillRect(renderer, &square_rect);
                    firstDraw(main_vector, renderer);
                    unBlockButton(renderer);
                    SDL_RenderPresent(renderer);
                }
            }
        }
    }
}

void Sort::destroy()
{
    SDL_DestroyTexture(change_button);
    SDL_DestroyTexture(change_disable);
    SDL_DestroyTexture(back_button);
    SDL_DestroyTexture(back_disable);
    SDL_DestroyTexture(selection_sort_button);
    SDL_DestroyTexture(selection_sort_disable);
    SDL_DestroyTexture(insertion_sort_button);
    SDL_DestroyTexture(insertion_sort_disable);
    SDL_DestroyTexture(bubble_sort_button);
    SDL_DestroyTexture(bubble_sort_disable);
    SDL_DestroyTexture(cancel_button);
    SDL_DestroyTexture(cancel_disable);
    SDL_DestroyTexture(interchange_sort_button);
    SDL_DestroyTexture(interchange_sort_disable);
    SDL_DestroyTexture(counting_sort_button);
    SDL_DestroyTexture(counting_sort_disable);
    SDL_DestroyTexture(quick_sort_button);
    SDL_DestroyTexture(quick_sort_disable);
    SDL_DestroyTexture(heap_sort_button);
    SDL_DestroyTexture(heap_sort_disable);
    SDL_DestroyTexture(merge_sort_button);
    SDL_DestroyTexture(merge_sort_disable);
    SDL_FreeCursor(cursor);
}

void Sort::blockButton(SDL_Renderer*& renderer)
{
    SDL_FreeCursor(cursor);
    SDL_RenderCopy(renderer, change_disable, NULL, &change_rect);
    SDL_RenderCopy(renderer, back_disable, NULL, &back_rect);
    SDL_RenderCopy(renderer, selection_sort_disable, NULL, &selection_sort_rect);
    SDL_RenderCopy(renderer, cancel_button, NULL, &cancel_rect);
    SDL_RenderCopy(renderer, insertion_sort_disable, NULL, &insertion_sort_rect);
    SDL_RenderCopy(renderer, bubble_sort_disable, NULL, &bubble_sort_rect);
    SDL_RenderCopy(renderer, interchange_sort_disable, NULL, &interchange_sort_rect);
    SDL_RenderCopy(renderer, counting_sort_disable, NULL, &counting_sort_rect);
    SDL_RenderCopy(renderer, quick_sort_disable, NULL, &quick_sort_rect);
    SDL_RenderCopy(renderer, heap_sort_disable, NULL, &heap_sort_rect);
    SDL_RenderCopy(renderer, merge_sort_disable, NULL, &merge_sort_rect);
}

void Sort::unBlockButton(SDL_Renderer*& renderer)
{
    SDL_RenderCopy(renderer, change_button, NULL, &change_rect);
    SDL_RenderCopy(renderer, back_button, NULL, &back_rect);
    SDL_RenderCopy(renderer, selection_sort_button, NULL, &selection_sort_rect);
    SDL_RenderCopy(renderer, cancel_disable, NULL, &cancel_rect);
    SDL_RenderCopy(renderer, insertion_sort_button, NULL, &insertion_sort_rect);
    SDL_RenderCopy(renderer, bubble_sort_button, NULL, &bubble_sort_rect);
    SDL_RenderCopy(renderer, interchange_sort_button, NULL, &interchange_sort_rect);
    SDL_RenderCopy(renderer, counting_sort_button, NULL, &counting_sort_rect);
    SDL_RenderCopy(renderer, quick_sort_button, NULL, &quick_sort_rect);
    SDL_RenderCopy(renderer, heap_sort_button, NULL, &heap_sort_rect);
    SDL_RenderCopy(renderer, merge_sort_button, NULL, &merge_sort_rect);
}

void Sort::threadManager(SDL_Renderer*& renderer)
{
    while (!exit_thread_manager)
    {
        if (!is_sorting && sort_thread.joinable())
        {
            sort_thread.join();
            std::this_thread::sleep_for(std::chrono::milliseconds(50));
            SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
            square_rect = { 10, 10, (WIDTH * 10) - 20, (HEIGHT * 10) - 200 };
            SDL_RenderFillRect(renderer, &square_rect);
            firstDraw(main_vector, renderer);
            SDL_RenderPresent(renderer);
        }
    }
}

void Sort::selectionSort(SDL_Renderer*& renderer, vector<int>& sort_vector, bool& is_sorting)
{
    if (renderer != NULL) blockButton(renderer);
    is_sorting = true;
    int min_pos;
    for (unsigned int i = 0; i < sort_vector.size() && is_sorting; i++)
    {
        min_pos = i;
        if (renderer != NULL)
        {
            SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
            SDL_RenderFillRect(renderer, &square_rect);
        }
        for (unsigned int j = i + 1; j < sort_vector.size() && is_sorting; j++)
        {
            if (sort_vector[j] < sort_vector[min_pos])
            {
                min_pos = j;
            }

            // // Draw
            if (renderer != NULL)
            {
                drawSelectionSort(sort_vector, renderer, i, min_pos, j);

                // // Show
                if (std::is_sorted(sort_vector.begin(), sort_vector.end()))
                {
                    unBlockButton(renderer);
                    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
                    SDL_RenderSetScale(renderer, 10, 10);
                    SDL_RenderDrawLine(renderer, sort_vector.size(), square_rect.h / 10 - sort_vector[sort_vector.size() - 1], sort_vector.size(), square_rect.h / 10);
                    SDL_RenderDrawLine(renderer, sort_vector.size() - 1, square_rect.h / 10 - sort_vector[sort_vector.size() - 2], sort_vector.size() - 1, square_rect.h / 10);
                    SDL_RenderDrawLine(renderer, sort_vector.size() - 2, square_rect.h / 10 - sort_vector[sort_vector.size() - 3], sort_vector.size() - 2, square_rect.h / 10);
                    SDL_RenderSetScale(renderer, 1, 1);
                } else {
                    std::this_thread::sleep_for(std::chrono::milliseconds(delay_time));
                }
                SDL_RenderPresent(renderer);
            }
        }
        if (renderer != NULL)
        {
            SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
            SDL_RenderFillRect(renderer, &square_rect);
            swap(sort_vector[min_pos], sort_vector[i]);
            drawSelectionSort(sort_vector, renderer, i, min_pos, min_pos);
            if (std::is_sorted(sort_vector.begin(), sort_vector.end()))
            {
                unBlockButton(renderer);
                SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
                SDL_RenderSetScale(renderer, 10, 10);
                SDL_RenderDrawLine(renderer, sort_vector.size(), square_rect.h / 10 - sort_vector[sort_vector.size() - 1], sort_vector.size(), square_rect.h / 10);
                SDL_RenderDrawLine(renderer, sort_vector.size() - 1, square_rect.h / 10 - sort_vector[sort_vector.size() - 2], sort_vector.size() - 1, square_rect.h / 10);
                SDL_RenderDrawLine(renderer, sort_vector.size() - 2, square_rect.h / 10 - sort_vector[sort_vector.size() - 3], sort_vector.size() - 2, square_rect.h / 10);
                SDL_RenderSetScale(renderer, 1, 1);
            } else {
                std::this_thread::sleep_for(std::chrono::milliseconds(delay_time));
            }
            SDL_RenderPresent(renderer);
        }
    }
    is_sorting = false;
}

void Sort::drawSelectionSort(std::vector<int> vector, SDL_Renderer* renderer,
 unsigned int green, unsigned int red, unsigned int blue)
{
    SDL_RenderSetScale(renderer, 10, 10);
    for (int i = 0; i < vector.size(); i++)
    {
        if (i == green) {
            SDL_SetRenderDrawColor(renderer, 125, 207, 182, 255);
        } else if (i == red) {
            SDL_SetRenderDrawColor(renderer, 251, 209, 162, 255);
        } else if (i == blue) {
            SDL_SetRenderDrawColor(renderer, 0, 178, 202, 255);
        } else {
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
        }
        SDL_RenderDrawLine(renderer, i + 1, square_rect.h / 10 - vector[i], i + 1, square_rect.h / 10);
    }
    SDL_RenderSetScale(renderer, 1, 1);
}

void Sort::insertionSort(SDL_Renderer*& renderer)
{
    blockButton(renderer);
    is_sorting = true;
    vector<int> sort_vector(main_vector.begin(), main_vector.end());
    int x, i, j;
    for (int i = 0; i < sort_vector.size() && is_sorting; i++)
    {
        x = sort_vector[i];
        j = i - 1;
        while (j >= 0 && x < sort_vector[j] && is_sorting)
        {
            SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
            SDL_RenderFillRect(renderer, &square_rect);
            swap(sort_vector[j + 1], sort_vector[j]);
            j--;
            drawInsertionSort(sort_vector, renderer, i, j+1);

            if (std::is_sorted(sort_vector.begin(), sort_vector.end()))
            {
                unBlockButton(renderer);
                SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
                SDL_RenderSetScale(renderer, 10, 10);
                SDL_RenderDrawLine(renderer, sort_vector.size(), square_rect.h / 10 - sort_vector[sort_vector.size() - 1], sort_vector.size(), square_rect.h / 10);
                SDL_RenderDrawLine(renderer, j + 2, square_rect.h / 10 - sort_vector[j + 1], j + 2, square_rect.h / 10);
                SDL_RenderSetScale(renderer, 1, 1);
            } else {
                std::this_thread::sleep_for(std::chrono::milliseconds(delay_time));
            }
            SDL_RenderPresent(renderer); 
        }
    }
    is_sorting = false;
}

void Sort::drawInsertionSort(vector<int> vector, SDL_Renderer* renderer,
 unsigned int green, unsigned int red)
{
    SDL_RenderSetScale(renderer, 10, 10);
    for (int i = 0; i < vector.size(); i++)
    {
        if (i == green) {
            SDL_SetRenderDrawColor(renderer, 125, 207, 182, 255);
        } else if (i == red) {
            SDL_SetRenderDrawColor(renderer, 251, 209, 162, 255);
        } else {
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
        }
        SDL_RenderDrawLine(renderer, i + 1, square_rect.h / 10 - vector[i], i + 1, square_rect.h / 10);
    }
    SDL_RenderSetScale(renderer, 1, 1);
}

void Sort::bubbleSort(SDL_Renderer*& renderer)
{
    blockButton(renderer);
    is_sorting = true;
    vector<int> sort_vector(main_vector.begin(), main_vector.end());
    for (int i = sort_vector.size() - 1; i >= 0 && is_sorting; i--)
    {
        for (int j = 0; j < i && is_sorting; j++)
        {
            SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
            SDL_RenderFillRect(renderer, &square_rect);
            if (sort_vector[j] > sort_vector[j + 1])
            {
                swap(sort_vector[j], sort_vector[j + 1]);
            }
            drawBubbleSort(sort_vector, renderer, j);
            if (std::is_sorted(sort_vector.begin(), sort_vector.end()))
            {
                unBlockButton(renderer);
                SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
                SDL_RenderSetScale(renderer, 10, 10);
                SDL_RenderDrawLine(renderer, 1, square_rect.h / 10 - sort_vector[0], 1, square_rect.h / 10);
                SDL_RenderDrawLine(renderer, 2, square_rect.h / 10 - sort_vector[1], 2, square_rect.h / 10);
                SDL_RenderSetScale(renderer, 1, 1);
            } else {
                std::this_thread::sleep_for(std::chrono::milliseconds(delay_time));
            }
            SDL_RenderPresent(renderer); 
        }
    }
    is_sorting = false;
}

void Sort::drawBubbleSort(vector<int> vector, SDL_Renderer* renderer, unsigned int red)
{
    SDL_RenderSetScale(renderer, 10, 10);
    for (int i = 0; i < vector.size(); i++)
    {
        if (i == red || i == red + 1) {
            SDL_SetRenderDrawColor(renderer, 251, 209, 162, 255);
        } else {
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
        }
        SDL_RenderDrawLine(renderer, i + 1, square_rect.h / 10 - vector[i], i + 1, square_rect.h / 10);
    }
    SDL_RenderSetScale(renderer, 1, 1);
}

void Sort::interchangeSort(SDL_Renderer*& renderer)
{
    blockButton(renderer);
    is_sorting = true;
    vector<int> sort_vector(main_vector.begin(), main_vector.end());
    for (int i = 0; i < sort_vector.size() && is_sorting; i++)
    {
        for (int j = i+1; j < sort_vector.size() && is_sorting; j++)
        {
            SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
            SDL_RenderFillRect(renderer, &square_rect);
            if (sort_vector[i] > sort_vector[j])
            {
                swap(sort_vector[i], sort_vector[j]);
            }
            drawInterchangeSort(sort_vector, renderer, i, j);
            if (std::is_sorted(sort_vector.begin(), sort_vector.end()))
            {
                unBlockButton(renderer);
                SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
                SDL_RenderSetScale(renderer, 10, 10);
                SDL_RenderDrawLine(renderer, sort_vector.size(), square_rect.h / 10 - sort_vector[sort_vector.size() - 1], sort_vector.size(), square_rect.h / 10);
                SDL_RenderDrawLine(renderer, sort_vector.size() - 1, square_rect.h / 10 - sort_vector[sort_vector.size() - 2], sort_vector.size() - 1, square_rect.h / 10);
                SDL_RenderSetScale(renderer, 1, 1);
            } else {
                std::this_thread::sleep_for(std::chrono::milliseconds(delay_time));
            }
            SDL_RenderPresent(renderer); 
        }
    }
    is_sorting = false;
}

void Sort::drawInterchangeSort(vector<int> vector, SDL_Renderer* renderer, unsigned int red, unsigned int blue)
{
    SDL_RenderSetScale(renderer, 10, 10);
    for (int i = 0; i < vector.size(); i++)
    {
        if (i == red) {
            SDL_SetRenderDrawColor(renderer, 251, 209, 162, 255);
        } else if (i == blue) {
            SDL_SetRenderDrawColor(renderer, 0, 178, 202, 255);
        } else {
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
        }
        SDL_RenderDrawLine(renderer, i + 1, square_rect.h / 10 - vector[i], i + 1, square_rect.h / 10);
    }
    SDL_RenderSetScale(renderer, 1, 1);
}

void Sort::countingSort(SDL_Renderer*& renderer)
{
    blockButton(renderer);
    is_sorting = true;
    vector<int> sort_vector(main_vector.begin(), main_vector.end());
    auto max_element = std::max_element(sort_vector.begin(), sort_vector.end());
    vector<int> counting_vector(static_cast<int>(*max_element));

    TTF_Font *font = TTF_OpenFont("fonts/arial.ttf", 25);
    SDL_Surface* element_surface = TTF_RenderText_Solid(font, "Element: ", {0, 153, 231, 255});
    SDL_Texture* element_texture = SDL_CreateTextureFromSurface(renderer, element_surface);
    SDL_Rect element_rect = {cancel_rect.x + cancel_rect.w + 5, cancel_rect.y, 70, 16};
    SDL_RenderCopy(renderer, element_texture, NULL, &element_rect);

    SDL_Surface* total_surface = TTF_RenderText_Solid(font, "Total: ", {0, 153, 231, 255});
    SDL_Texture* total_texture = SDL_CreateTextureFromSurface(renderer, total_surface);
    SDL_Rect total_rect = {cancel_rect.x + cancel_rect.w + 5, cancel_rect.y + element_rect.h, 40, 16};
    SDL_RenderCopy(renderer, total_texture, NULL, &total_rect);

    for (int i = 0; i < counting_vector.size() && is_sorting; i++)
    {
        std::string numberString;
        if (i + 1 < 10) {
            numberString = "0" + std::to_string(i + 1);
        } else {
            numberString = std::to_string(i + 1);
        }

        SDL_Surface* counting_surface = TTF_RenderText_Solid(font, numberString.c_str(), {0, 153, 231, 255});
        SDL_Texture* counting_texture = SDL_CreateTextureFromSurface(renderer, counting_surface);

        SDL_Rect first_counting_rect = {element_rect.x + element_rect.w + 17*i, cancel_rect.y, 12, 15};
        SDL_RenderCopy(renderer, counting_texture, NULL, &first_counting_rect);
        
        SDL_RenderPresent(renderer);

        SDL_FreeSurface(counting_surface);
        SDL_DestroyTexture(counting_texture);
    }

    SDL_Rect total_square_rect = { element_rect.x + element_rect.w, cancel_rect.y + element_rect.h, 
    square_rect.x + square_rect.w - (element_rect.x + element_rect.w), total_rect.h };

    renderTotal(counting_vector, renderer, total_square_rect, is_sorting, font, element_rect, total_rect);

    for (int i = 0; i < sort_vector.size() && is_sorting; i++)
    {
        SDL_RenderSetScale(renderer, 10, 10);
        SDL_SetRenderDrawColor(renderer, 251, 209, 162, 255);
        SDL_RenderDrawLine(renderer, i + 1, square_rect.h / 10 - sort_vector[i], i + 1, square_rect.h / 10);
        SDL_RenderSetScale(renderer, 1, 1);
        SDL_RenderPresent(renderer);
        std::this_thread::sleep_for(std::chrono::milliseconds(delay_time * 50));
        counting_vector[sort_vector[i] - 1]++;
        SDL_RenderSetScale(renderer, 10, 10);
        SDL_SetRenderDrawColor(renderer, 0, 153, 231, 255);
        SDL_RenderDrawLine(renderer, i + 1, square_rect.h / 10 - sort_vector[i], i + 1, square_rect.h / 10);
        SDL_RenderSetScale(renderer, 1, 1);
        renderTotal(counting_vector, renderer, total_square_rect, is_sorting, font, element_rect, total_rect);
        SDL_RenderPresent(renderer);
        std::this_thread::sleep_for(std::chrono::milliseconds(delay_time * 50));
    }
    int sort_index = 0;
    for (int i = 0; i < counting_vector.size() && is_sorting; i++)
    {
        while (counting_vector[i] > 0 && is_sorting)
        {
            sort_vector[sort_index] = i + 1;
            renderTotal(counting_vector, renderer, total_square_rect, is_sorting, font, element_rect, total_rect);
            SDL_RenderSetScale(renderer, 10, 10);
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
            SDL_RenderDrawLine(renderer, sort_index + 1, square_rect.h / 10 - sort_vector[sort_index], sort_index + 1, square_rect.h / 10);
            SDL_RenderSetScale(renderer, 1, 1);
            SDL_RenderPresent(renderer);
            std::this_thread::sleep_for(std::chrono::milliseconds(delay_time * 50));
            sort_index++;
            counting_vector[i] --;
        }
    }

    SDL_Rect full_rect = { cancel_rect.x + cancel_rect.w + 5, cancel_rect.y, 
    square_rect.w - (cancel_rect.x + cancel_rect.w), cancel_rect.h };
    SDL_SetRenderDrawColor(renderer, 239, 241, 250, 255);    
    SDL_RenderFillRect(renderer, &full_rect);
    unBlockButton(renderer);
    SDL_RenderPresent(renderer);

    is_sorting = false;
}

void Sort::renderTotal(vector<int> vector, SDL_Renderer* renderer, SDL_Rect square_rect, bool is_sorting,
 TTF_Font *font, SDL_Rect element_rect, SDL_Rect total_rect)
{
    SDL_SetRenderDrawColor(renderer, 239, 241, 250, 255);    
    SDL_RenderFillRect(renderer, &square_rect);

    for (int i = 0; i < vector.size() && is_sorting; i++)
    {
        std::string numberString;
        if (vector[i] < 10) {
            numberString = "0" + std::to_string(vector[i]);
        } else {
            numberString = std::to_string(vector[i]);
        }

        SDL_Surface* counting_surface = TTF_RenderText_Solid(font, numberString.c_str(), {0, 153, 231, 255});
        SDL_Texture* counting_texture = SDL_CreateTextureFromSurface(renderer, counting_surface);

        SDL_Rect first_counting_rect = {element_rect.x + element_rect.w + 17*i, total_rect.y, 12, 15};
        SDL_RenderCopy(renderer, counting_texture, NULL, &first_counting_rect);
        
        SDL_RenderPresent(renderer);

        SDL_FreeSurface(counting_surface);
        SDL_DestroyTexture(counting_texture);
    }
}

void Sort::quickSort(SDL_Renderer*& renderer, vector<int>& sort_vector, int left, int right)
{
    blockButton(renderer);
    SDL_RenderPresent(renderer);
    is_sorting = true;

    int mid = sort_vector[(left + right) / 2];
    int i = left;
    int j = right;

    while (i <= j)
    {
        while (sort_vector[i] < mid) {
            i++;
        }
        while (sort_vector[j] > mid) j--;
        if (i <= j)
        {
            swap(sort_vector[i], sort_vector[j]);
            i++;
            j--;
        }
    }

    if (left < j) quickSort(renderer, sort_vector, left, j);
    if (i < right) quickSort(renderer, sort_vector, i, right);

    if (std::is_sorted(sort_vector.begin(), sort_vector.end()))
    {
        unBlockButton(renderer);
        SDL_RenderPresent(renderer);
        is_sorting = false;
        for (int i: sort_vector)
        {
            std::cout<<i<<" ";
        }
    } else {
        // std::this_thread::sleep_for(std::chrono::milliseconds(delay_time));
    }
}

// void Sort::drawQuickSort(std::vector<int> vector, SDL_Renderer* renderer,
//  unsigned int green, unsigned int red_left, unsigned int red_right)
// {
//     SDL_RenderSetScale(renderer, 10, 10);
//     for (int i = 0; i < vector.size(); i++)
//     {
//         if (i == green) {
//             SDL_SetRenderDrawColor(renderer, 125, 207, 182, 255);
//         } else if (i == red_left || i == red_right) {
//             SDL_SetRenderDrawColor(renderer, 251, 209, 162, 255);
//         } else {
//             SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
//         }
//         SDL_RenderDrawLine(renderer, i + 1, square_rect.h / 10 - vector[i], i + 1, square_rect.h / 10);
//     }
//     SDL_RenderSetScale(renderer, 1, 1);
// }

/************************************************************/

static void *_cffi_types[] = {
  0
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  NULL,  /* no globals */
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  0,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  0,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_sort_(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_sort_(void) { return NULL; }
#  else
     initsort_(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_sort_(void)
{
  return _cffi_init("sort_", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initsort_(void)
{
  _cffi_init("sort_", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
